apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: myappset
  namespace: default
spec:
  generators:
  - git:
      repoURL: https://github.com/sinotna/Gitops.git
      revision: main
      directories:
      - path: "/Apps/*"
  template:
    metadata:
      name: '{{ "{{" }}path.basename{{ "}}" }}' # name of the application
    spec:
      project: 'default' # all Applications are created on project 'default'
      source:
        repoURL: https://github.com/sinotna/Gitops.git
        targetRevision: main # can be set via the cluster config.json
        path: '{{ "{{" }}path{{ "}}" }}'
        helm:
          ignoreMissingValueFiles: true
          valueFiles:
          - values.yaml
          - values-env.yaml
      destination:
        server: 'https://kubernetes.default.svc' # default value
        namespace: tools
      syncPolicy:
        automated:
          prune: true
          selfHeal: false
