---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: gitops-appset
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: 'https://github.com/sinotna/Gitops.git'
      revision: applicationsets
      files:
      - path: "*/*/values.yaml"
  template:
    metadata:
      name: "{{ .Values.appsetTemplates.pathBasename | quote }}" # name of the application
    spec:
      project: 'default' # all Applications are created on project 'default'
      source:
        repoURL: 'https://github.com/sinotna/Gitops.git'
        targetRevision: applicationsets # can be set via the cluster config.json
        path: "{{ .Values.appsetTemplates.path | quote }}"
        helm:
          ignoreMissingValueFiles: true
          valueFiles:
          - values.yaml
      destination:
        server: 'https://kubernetes.default.svc' # default value
        namespace: "{{ .Values.appsetTemplates.namespace | quote }}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: false
