apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: gitops-appset
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: 'https://github.com/sinotna/Gitops.git'
      revision: applicationsets
      files:
      - path: "*/*/values.yaml"
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: 'default'
      source:
        repoURL: 'https://github.com/sinotna/Gitops.git'
        targetRevision: applicationsets
        path: "{{path}}"
        helm:
          valueFiles:
          - values.yaml
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: false