apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubernetes-dashboard
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sinotna/Gitops.git
    targetRevision: HEAD
    path: app-root
  destination: 
    server: https://kubernetes.default.svc
    namespace: default