---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/sinotna/Gitops.git
      revision: sealed-secrets
      directories:
      - path: "/Tools/sealed-secrets/*"
  template:
    metadata:
      name: '{{ path.basename }}' # name of the application
    spec:
      project: 'default' # all Applications are created on project 'default'
      source:
        repoURL: https://github.com/sinotna/Gitops.git
        targetRevision: sealed-secrets # can be set via the cluster config.json
        path: '{{ path }}'
        helm:
          ignoreMissingValueFiles: true
          valueFiles:
          - values.yaml
      destination:
        server: 'https://kubernetes.default.svc' # default value
        namespace: kube-system
      syncPolicy:
        automated:
          prune: true
          selfHeal: false
...