# allow all incoming traffic
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: sealed-secrets-allow-incoming-traffic
  namespace: sealed-secrets
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: sealed-secrets
  ingress:
    - {}