apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-apps
  namespace: default
spec:
  destination:
    namespace: platform-applications
    server: https://kubernetes.default.svc
  project: platform
  source:
    path: applications
    repoURL: "https://github.com/sinotna/GitOps-Apps.git"
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
